import { sequelize } from "../config/sequelize.js";
import { Product } from "../models/Product.js";

const products = [
  // ===== DRINK =====
  {
    name: "Trà sữa đóng chai",
    description: "Đồ uống trà sữa tiện lợi, vị ngọt béo dễ uống",
    price: 22000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644227/product_drink_traSua_nyufn4.jpg",
    category: "drink",
    quantity: 15,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Cà phê đen lon",
    description: "Cà phê đậm vị, giúp tỉnh táo nhanh",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644227/product_drink_caPheLon_ek0rvo.jpg",
    category: "drink",
    quantity: 12,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Nước tăng lực Sting",
    description: "Bổ sung năng lượng nhanh chóng",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_Sting_u4q52i.jpg",
    category: "drink",
    quantity: 20,
    brand: "Pepsico",
    rating: 4,
  },
  {
    name: "Nước cam ép",
    description: "Nước trái cây thanh mát, giàu vitamin C",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_nuocCam_o4yvw4.webp",
    category: "drink",
    quantity: 10,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "Sữa tươi tiệt trùng",
    description: "Bổ sung dinh dưỡng cho cả ngày",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_suaVinamilk_ntev6v.jpg",
    category: "drink",
    quantity: 18,
    brand: "Vinamilk",
    rating: 5,
  },
  {
    name: "Trà xanh đóng chai",
    description: "Thanh mát, hỗ trợ giải nhiệt",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_traXanhLon_yqh3kx.png",
    category: "drink",
    quantity: 14,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Coca Cola lon",
    description: "Nước ngọt có ga quen thuộc",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_cocaCola_kgqpnw.jpg",
    category: "drink",
    quantity: 20,
    brand: "Coca Cola",
    rating: 5,
  },
  {
    name: "Pepsi lon",
    description: "Nước giải khát có ga",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_pepsi_qzxqua.jpg",
    category: "drink",
    quantity: 18,
    brand: "Pepsi",
    rating: 5,
  },
  {
    name: "7Up lon",
    description: "Nước chanh có ga",
    price: 14000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_7up_lnrmx3.jpg",
    category: "drink",
    quantity: 15,
    brand: "PepsiCo",
    rating: 4,
  },
  {
    name: "Trà Ô Long Tea+",
    description: "Trà thanh nhẹ dễ uống",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644226/product_drink_traOLong_edfdse.jpg",
    category: "drink",
    quantity: 12,
    brand: "Suntory",
    rating: 5,
  },

  // ===== FOOD =====
  {
    name: "Mì ly bò cay Hàn Quốc",
    description: "Mì ăn liền cay nồng",
    price: 28000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644630/product_food_myLyBoCay_m0qvml.webp",
    category: "food",
    quantity: 9,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Cơm hộp gà teriyaki",
    description: "Cơm đầy đủ dinh dưỡng",
    price: 50000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644630/product_food_comHop_ylikkm.jpg",
    category: "food",
    quantity: 7,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Bánh mì kẹp thịt nguội",
    description: "Bữa sáng tiện lợi",
    price: 25000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644629/product_food_banhMiKep_gcbwvj.jpg",
    category: "food",
    quantity: 11,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "Cơm nắm Onigiri",
    description: "Cơm nắm tiện lợi",
    price: 25000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644630/product_food_comNam_pphur5.jpg",
    category: "food",
    quantity: 8,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "Xúc xích tiệt trùng",
    description: "Ăn nhanh tiện lợi",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644629/product_food_xucXic_mrodav.webp",
    category: "food",
    quantity: 15,
    brand: "CP",
    rating: 4,
  },
  {
    name: "Mì ly hải sản",
    description: "Mì vị hải sản đậm đà",
    price: 25000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644630/product_food_myLyHaiSan_ojby9r.jpg",
    category: "food",
    quantity: 10,
    brand: "Acecook",
    rating: 5,
  },
  {
    name: "Sandwich trứng",
    description: "Bữa sáng nhanh gọn",
    price: 30000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644629/product_food_sandwichTrung_iwoaad.jpg",
    category: "food",
    quantity: 8,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Cơm bò sốt tiêu",
    description: "Cơm nóng kèm bò đậm vị",
    price: 55000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644630/product_food_comBoTieu_s1mppp.jpg",
    category: "food",
    quantity: 6,
    brand: "Convenience Store",
    rating: 5,
  },

  // ===== SNACK =====
  {
    name: "Snack khoai tây giòn",
    description: "Snack giòn ngon",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644945/product_snack__snackKhoaiTay_fg9xvf.jpg",
    category: "snack",
    quantity: 20,
    brand: "Oishi",
    rating: 5,
  },
  {
    name: "Bánh mì kem",
    description: "Bánh ngọt nhẹ",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644944/product_snack__banhMiKem_pkqruu.jpg",
    category: "snack",
    quantity: 13,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Kẹo bạc hà",
    description: "Kẹo thơm miệng",
    price: 8000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644944/product_snack_keoBacHa_bz4e0g.webp",
    category: "snack",
    quantity: 17,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "Bánh mì ngọt",
    description: "Bánh mềm ngọt tiện lợi",
    price: 15000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644945/product_snack_banhMiNgot_wuxbqt.jpg",
    category: "snack",
    quantity: 10,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "Snack rong biển",
    description: "Giòn nhẹ, ăn không ngán",
    price: 12000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644943/product_snack__snackRongBien_rpl6wq.jpg",
    category: "snack",
    quantity: 9,
    brand: "Convenience Store",
    rating: 4,
  },
  {
    name: "KitKat chocolate",
    description: "Bánh chocolate giòn",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644942/product_snack_kitkatChoco_yaqerx.webp",
    category: "snack",
    quantity: 15,
    brand: "Nestle",
    rating: 5,
  },
  {
    name: "Oreo bánh quy",
    description: "Bánh quy kẹp kem",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644942/product_snack__oreo_ykrw5b.jpg",
    category: "snack",
    quantity: 16,
    brand: "Oreo",
    rating: 5,
  },
  {
    name: "Pocky dâu",
    description: "Snack que phủ socola",
    price: 17000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644942/product_snack__pockyDau_jfqpcp.jpg",
    category: "snack",
    quantity: 12,
    brand: "Glico",
    rating: 5,
  },
  {
  name: "Bánh Tiramisu",
  description: "Bánh ngọt mềm mịn, vị cà phê nhẹ và béo ngậy",
  price: 22000,
  image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644943/product_snack__banhTiramisu_pcy8iz.png",
  category: "snack",
  quantity: 10,
  brand: "Convenience Store",
  rating: 5,
  },
  {
    name: "Pudding trứng",
    description: "Tráng miệng mềm mịn, ngọt nhẹ, dễ ăn",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777644943/product_snack__puddingTrung_cg1cne.jpg",
    category: "snack",
    quantity: 12,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Bánh flan caramel",
    description: "Món tráng miệng mềm mịn, thơm vị caramel",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777645941/product_snack__banhCaramel_sifzz3.png",
    category: "snack",
    quantity: 10,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Bánh su kem",
    description: "Vỏ bánh mềm, nhân kem béo nhẹ",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777645941/product_snack__banhSukem_fap1ir.jpg",
    category: "snack",
    quantity: 9,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Snack bắp rang bơ",
    description: "Bắp rang giòn, vị bơ thơm nhẹ",
    price: 18000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777645941/product_snack__snackBapRang_vdo0bv.jpg",
    category: "snack",
    quantity: 14,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Thanh protein chocolate",
    description: "Thanh ăn nhẹ bổ sung năng lượng nhanh",
    price: 25000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777645939/product_snack__thanhProteinSocola_dqnqfm.jpg",
    category: "snack",
    quantity: 8,
    brand: "Convenience Store",
    rating: 5,
  },

  // ===== DAILY =====
  {
    name: "Khăn giấy",
    description: "Dùng hằng ngày",
    price: 10000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646005/product_daily__khanGiay_rgzk3a.png",
    category: "daily",
    quantity: 20,
    brand: "Pampers",
    rating: 4,
  },
  {
    name: "Nước rửa tay",
    description: "Kháng khuẩn tiện lợi",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646005/product_daily__nuocRuaTay_nxh6oq.jpg",
    category: "daily",
    quantity: 14,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Khẩu trang",
    description: "Dùng một lần tiện lợi",
    price: 12000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646004/product_daily__khauTrang_l7slid.png",
    category: "daily",
    quantity: 18,
    brand: "Convenience Store",
    rating: 5,
  },
  {
    name: "Dầu gội",
    description: "Chăm sóc tóc",
    price: 35000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646004/product_daily__dauGoi_nab1xj.webp",
    category: "daily",
    quantity: 7,
    brand: "Dove",
    rating: 5,
  },
  {
    name: "Sữa tắm",
    description: "Chăm sóc cơ thể",
    price: 35000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646003/product_daily__suaTam_ajk8eh.jpg",
    category: "daily",
    quantity: 11,
    brand: "Nivea",
    rating: 5,
  },
  {
    name: "Bàn chải đánh răng",
    description: "Dụng cụ vệ sinh cá nhân",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646003/product_daily__banChai_aimq2o.png",
    category: "daily",
    quantity: 10,
    brand: "Colgate",
    rating: 5,
  },
  {
    name: "Kem đánh răng",
    description: "Giữ răng sạch khỏe",
    price: 20000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646002/product_daily__kemDanhRang_ufe4re.jpg",
    category: "daily",
    quantity: 12,
    brand: "Colgate",
    rating: 5,
  },
  {
    name: "Lăn khử mùi",
    description: "Giữ cơ thể thơm mát",
    price: 40000,
    image: "https://res.cloudinary.com/dicsf4zkz/image/upload/v1777646002/product_daily__lanKhuMui_voitdj.jpg",
    category: "daily",
    quantity: 8,
    brand: "Nivea",
    rating: 5,
  },
];

async function seed() {
  try {
    await sequelize.authenticate();
    console.log("Connected DB");

    await sequelize.query("SET FOREIGN_KEY_CHECKS = 0");
    await Product.destroy({ where: {}, truncate: true });
    await Product.bulkCreate(products);

    console.log("SEED DONE (50+ PRODUCTS)");
  } catch (err) {
    console.error(err);
  } finally {
    await sequelize.query("SET FOREIGN_KEY_CHECKS = 1");
    process.exit();
  }
}

seed();